export const DOMAIN_API = 'http://222.255.180.18/api/'
export const UPLOAD_API = 'medical-record/extract'
export const SAVE_RECORD = 'medical-record/save'
export const SEND_EMAIL_RESET = 'auth/forgot-password'
export const RESET_PASSWORD = 'auth/reset-password'
export const GET_RECORDS = 'medical-record'
export const GET_ME = 'auth/me'
export const DETAIL_RECORD = 'medical-record/'
export const DOWNLOAD_RECORD = 'medical-record/download/'
export const LOGIN = 'auth/login'
export const GET_PROFILE = 'profile/me'
export const UPDATE_PROFILE = 'profile/update'

// Chat APIs
export const CHAT = 'chat'
export const NEW_CHAT = 'chat/new'
export const GET_CONVERSATIONS = 'chat/conversations'
export const GET_CHAT_HISTORY = 'chat/history/'