export const DOMAIN_API = 'http://localhost:5062/api/'
export const UPLOAD_API = 'medical-record/extract'
export const SAVE_RECORD = 'medical-record/save'
export const SEND_EMAIL_RESET = 'auth/forgot-password'
export const RESET_PASSWORD = 'auth/reset-password'
export const GET_RECORDS = 'medical-record'
export const GET_ME = 'auth/me'
export const DETAIL_RECORD = 'medical-record/'